feat(#9): basic player movement
grupacosmo/cosmobot pull request #21
Opened 2024-02-11 21:56 UTC by Acu1000

close #9

2024-02-15 13:05 UTC, PatrykPaluch requested changes

2024-02-15 13:05 UTC, PatrykPaluch commented on Assets/Scripts/PlayerCharacter/PlayerController.cs
> +        }
Use new InputSystem. It is already configured in project, if you need to change something, check `Assets/ProjectConfig/DefaultInputActions` asset.

I like approach with generated interface: [Using Input Action Assets](https://docs.unity3d.com/Packages/com.unity.inputsystem@1.8/manual/ActionAssets.html#using-input-action-assets)
```cs
// implement generated interface
public class PlayerController : MonoBehaviour, DefaultInputActions.IPlayerMovementActions
    {
        DefaultInputActions actions;
        
        // override method from interface
        public void OnMovement(InputAction.CallbackContext context) {
            Debug.Log(context.ReadValue<Vector2>()); // read value
        }

        void OnEnable() {
            if(actions == null) {
                actions = new DefaultInputActions();
                actions.PlayerMovement.SetCallbacks(this);
            }
            actions.PlayerMovement.Enable();
        }
        void OnDisable() {
            actions.PlayerMovement.Disable();
        }
        //...
}
```
  
But, there is also more popular approach with `PlayerInput` Asset: [Using Action Assets with PlayerInput](https://docs.unity3d.com/Packages/com.unity.inputsystem@1.8/manual/ActionAssets.html#using-action-assets-with-playerinput).

InputSystem tutorial: https://docs.unity3d.com/Packages/com.unity.inputsystem@1.8/manual/ActionsEditor.html

2024-02-15 13:05 UTC, PatrykPaluch commented on Assets/Scripts/PlayerCharacter/PlayerController.cs
> +    public class PlayerController : MonoBehaviour
missing camera/rotation?

2024-02-15 13:05 UTC, PatrykPaluch commented on Assets/Scripts/PlayerCharacter/PlayerController.cs
> +            float radius = 0.45f;
Extract to fields, same as `groundNormal`

2024-02-15 13:05 UTC, PatrykPaluch commented on Assets/Scripts/PlayerCharacter/PlayerController.cs
> +            Physics.SphereCast(origin, radius, Vector3.down, out hitInfo, 0.6f);
`0.6` - magic number

2024-02-15 13:05 UTC, PatrykPaluch commented on Assets/Scripts/PlayerCharacter/PlayerController.cs
> +            rb = GetComponent<Rigidbody>();
You can add `[RequireComponent(typeof(Rigidbody))]` attribute to class to make Unity automatically add `Rigidbody` along with this component

2024-02-15 13:05 UTC, PatrykPaluch commented on Assets/Scripts/PlayerCharacter/PlayerController.cs
> +            rb = GetComponent<Rigidbody>();
I understand that you setup Rigidbody in inspector. But im think it would be nice to setup Rigidbody here, in `Start()`. Do whatever you prefer.

2024-02-15 13:25 UTC, Acu1000 commented on Assets/Scripts/PlayerCharacter/PlayerController.cs
> +    public class PlayerController : MonoBehaviour
Camera seems to be someone else's task https://trello.com/c/Ivv3hlAM/8-zmienianie-kamery

2024-02-15 13:26 UTC, PatrykPaluch commented on Assets/Scripts/PlayerCharacter/PlayerController.cs
> +    public class PlayerController : MonoBehaviour
ok

2024-02-20 20:14 UTC, PatrykPaluch approved these changes

2024-02-20 21:45 UTC, merged