feat(#25): camera and movement collaboration
grupacosmo/cosmobot pull request #29
Opened 2024-02-27 01:42 UTC by Beholder1

2024-02-28 20:00 UTC, Acu1000 commented on Assets/Scripts/PlayerCharacter/PlayerController.cs
I believe instead of making the player always face the camera's direction there should be an option to toggle that with an enum or bool variable

I think we should discuss the changes in this script in person next time we meet

2024-02-28 20:05 UTC, Beholder1 commented on Assets/Scripts/PlayerCharacter/PlayerController.cs
Yeah, you're right. I think most games do it so when you hold right click while rotating the camera, it just rotates around the player and the player object doesn't rotate. But as you said, it would be nice to discuss it in person.

2024-03-01 18:30 UTC, PatrykPaluch requested changes

2024-03-01 18:30 UTC, PatrykPaluch commented on Assets/Scripts/Camera/PlayerCamera.cs
>              var cameraDistance = (float)Math.Sqrt(Math.Pow(cameraChangeZ, 2f) + Math.Pow(cameraChangeY, 2f));
we dont use `var`

2024-03-01 18:30 UTC, PatrykPaluch commented on Assets/Scripts/PlayerCharacter/PlayerController.cs
> +            var shouldJump = inputJump && isGrounded;
`var` again

2024-03-05 11:40 UTC, PatrykPaluch requested changes

2024-03-05 11:40 UTC, PatrykPaluch commented on Assets/Scripts/Camera/PlayerCamera.cs
> +                    88f - cameraChangeY / cameraChangeZ * 45f);
:magic_wand: :1234:

2024-03-05 11:40 UTC, PatrykPaluch commented on Assets/Scripts/PlayerCharacter/PlayerController.cs
>              groundCheckOrigin = transform.Find("GroundCheckOrigin");
i would prefer to make `groundCheckOrigin` `[SerializableField]` to avoid ambiguous names in GameObject names. In code, we have some kind of control over strings values, (eg. const), but there is no connection between string in script and GameObject name.

2024-03-05 11:40 UTC, PatrykPaluch commented on Assets/Scripts/PlayerCharacter/PlayerController.cs
>          private void GroundCheck()
With some luck, player can jump twice resulting in twice as high jump. You can add `velocity.y < 0.01` as additional check to prevent this

2024-03-05 11:40 UTC, PatrykPaluch commented on Assets/Scripts/PlayerCharacter/PlayerController.cs
> +            if (inputMove.magnitude < 0.1f) return;
[sqrMagnitude](https://docs.unity3d.com/ScriptReference/Vector3-sqrMagnitude.html)

2024-03-05 11:45 UTC, PatrykPaluch commented
![image](https://github.com/grupacosmo/cosmobot/assets/4960296/759da433-2e85-4b7e-b3ed-654437720bcb)

And fix this spammer :P

2024-03-05 12:50 UTC, Acu1000 submitted a review, later dismissed

2024-03-05 20:57 UTC, PatrykPaluch approved these changes

2024-03-05 21:04 UTC, merged