feat(#3): player, power station, iron and titanium models
grupacosmo/cosmobot pull request #5
Opened 2023-12-07 16:40 UTC by kishieel

**Preview:**

Player:
![image](https://github.com/grupacosmo/cosmobot/assets/49162745/86d9e76e-591a-4f29-9476-db6b04d96a52)

Power Station:
![image](https://github.com/grupacosmo/cosmobot/assets/49162745/84c97169-e2d7-40ad-a185-a594e4d8da91)

Minerals and Ores:
![image](https://github.com/grupacosmo/cosmobot/assets/49162745/31503381-736d-483e-b516-a96063cc6b57)

2023-12-09 22:47 UTC, PatrykPaluch requested changes
Space in filename can cause issues. Also, i would organize models into directories, eg. Items, Items/Ores, Structures, Characters

2023-12-10 16:18 UTC, PatrykPaluch requested changes
merge/rebase main to your branch to enable github actions

Answer: Rebased

2024-03-02 10:04 UTC, kishieel commented
Test

2024-03-03 16:32 UTC, PatrykPaluch approved these changes

2024-03-03 16:38 UTC, merged