feat(#51): proper player prefab
grupacosmo/cosmobot pull request #57
Opened 2024-04-16 19:09 UTC by Acu1000

Player prefab can now be added to any scene without extra work

closes #51

2024-04-16 20:14 UTC, Vie0n approved these changes, later dismissed

2024-04-16 20:38 UTC, PatrykPaluch requested changes

2024-04-16 20:38 UTC, PatrykPaluch commented on Assets/Prefabs/Player/Player.prefab
>    m_Component:
- Add `PlayerInteractionHandler` component
- Add "Gravity Gun" 

Idk how to handle GUI for player. For now only `PlayerInteractionHandler` requires UI, but in the future, there will be more components that connects to UI. I think, for now, we can create new prefab for in game UI and just manually drag'n'drop required references.

2024-04-17 17:32 UTC, PatrykPaluch approved these changes

2024-04-17 17:33 UTC, merged