feat(#60): building placement
grupacosmo/cosmobot pull request #68
Opened 2024-11-29 18:19 UTC by Acu1000

closes #60

2024-12-12 10:45 UTC, Vie0n requested changes

2024-12-12 10:45 UTC, Vie0n commented on Assets/Scripts/BuildingSystem/BuildingInfo.cs
> +        public bool Equals(BuildingInfo other) => other != null && id == other.id;
```suggestion
        public bool Equals(BuildingInfo other) => other is not null && id == other.id;
```

2024-12-12 10:45 UTC, Vie0n commented on Assets/Scripts/Construction/PlayerConstructionHandler.cs
> +            }
It's always better to invert the statements to avoid needless nesting. In this case:
```if (isPlacementActive is false) return;```

2024-12-12 10:45 UTC, Vie0n commented on Assets/Scripts/Construction/PlayerConstructionHandler.cs
> +            }
I would move BoxCast inside if but thats just my opinion.
```c#
    if (Physics.BoxCast(
        boxOrigin,
        boxHalfExtents,
        Vector3.down,
        out RaycastHit hitResult,
        buildingRotation,
        maxTerrainHeight * 2,
        buildTargetingCollisionMask))
    {
    ...
    }
```

2024-12-12 10:45 UTC, Vie0n commented on Assets/Scripts/Construction/PlayerConstructionHandler.cs
> +        }
I would suggest changing the name of this function to CalculateBuildingPlacement, also remove both setActive and constructionPreview.SetPosition from this function. We only want to calculate the building placement in here. We can SetActive and preview inside ProcessPlacement as it is a more general function. Let's not make 'Ultimate functions'. Use the nullable vector to determine if we need to change the state.

2024-12-12 10:45 UTC, Vie0n commented on Assets/Scripts/Construction/PlayerConstructionHandler.cs
> +            constructionPreview.SetPosition(finalPlacementPosition);
SetActive and constructPreview.SetPosition are atomic. That means when we call the first one we also want to call the other one. I would create the function that calls both so we can avoid situations where we call one but forget the other.

2024-12-12 10:45 UTC, Vie0n commented on Assets/Scripts/Construction/PlayerConstructionHandler.cs
> +        private void RotatePlacement(bool reverse=false)
Spaces
```suggestion
        private void RotatePlacement(bool reverse = false) 
```

2024-12-12 10:45 UTC, Vie0n commented on Assets/Scripts/Buildings/BaseBuilding.cs
> +        public BuildingInfo buildingInfo {get; protected set;}
```suggestion
        public BuildingInfo buildingInfo { get; protected set; }
```

2024-12-12 21:52 UTC, Acu1000 commented on Assets/Scripts/Construction/PlayerConstructionHandler.cs
> +            constructionPreview.SetPosition(finalPlacementPosition);
I could put `SetActive(true)` inside `SetPosition`, but I believe that'd make code less readable - with `SetActive(false)` being there, it makes sense for the opposite to also be visible in the same place

2024-12-13 12:45 UTC, Vie0n submitted a review, later dismissed

2024-12-13 18:59 UTC, PatrykPaluch approved these changes

2024-12-13 19:06 UTC, merged