feat(#71): Grid Display
grupacosmo/cosmobot pull request #79
Opened 2024-12-16 21:07 UTC by StaszkeKun

Simple customizable grid shader for building.
![image](https://github.com/user-attachments/assets/75e155e6-0960-429f-80d5-41254e256297)

Closes #71

2024-12-17 08:34 UTC, Acu1000 requested changes

2024-12-17 08:34 UTC, Acu1000 commented on Assets/Scripts/Construction/PlayerConstructionHandler.cs
> +            gridDisplay.SetActive(false);
Since GridDisplay and ConstructionPreview objects are effectively bound together anyway (they're always enabled or disabled together), the gridDisplay should be managed by the ConstructionPreview script, to avoid situations where we call one function but forget the other (and to keep the code cleaner). Or perhaps you can achieve that by making GridDisplay object a child of ConstructionPreview

If you intend to keep GridDisplay as a standalone object, make it into a prefab

2024-12-17 08:34 UTC, Acu1000 commented on Assets/Shaders/GridDisplay.shader
The grid should also display on uneven terrain, since that's what the player will be building on most of the time (though that might be hard to implement and test before #73 ). You can try to implement it now if you want, or we can leave it for a future task, the choice is yours

2024-12-17 22:07 UTC, Vie0n approved these changes

2024-12-17 22:09 UTC, Vie0n requested changes
Basically fix what @Acu1000 requested.

2024-12-20 08:48 UTC, StaszkeKun commented on Assets/Scripts/Construction/PlayerConstructionHandler.cs
> +            gridDisplay.SetActive(false);
gridDisplay is now managed by the ConstructionPreview script and is made child of it.

2024-12-20 08:52 UTC, StaszkeKun commented on Assets/Shaders/GridDisplay.shader
Grid now displays on uneven terrain.
Terrain now needs to use "terrain" material for the grid to display.

2024-12-21 20:19 UTC, Vie0n commented on Assets/Scripts/Construction/ConstructionPreview.cs
> +        }
```suggestion
            gridDisplayTransform.position = newPosition;
        }
```

2024-12-21 20:20 UTC, Vie0n approved these changes, later dismissed

2025-01-10 17:38 UTC, Acu1000 approved these changes

2025-01-10 17:43 UTC, merged