feat(#56): Animations implementation
grupacosmo/cosmobot pull request #82
Opened 2024-12-31 19:04 UTC by Beholder1

2025-01-06 15:46 UTC, PatrykPaluch requested changes

2025-01-06 15:46 UTC, PatrykPaluch commented on Assets/Scripts/PlayerCharacter/PlayerController.cs
> +        private static readonly int Jump = Animator.StringToHash("jump");
prefix variables with `Prop` or `Animator` or something so it's obvious that this is Animator Property

2025-01-31 19:22 UTC, Acu1000 submitted a review, later dismissed

2025-01-31 19:35 UTC, Acu1000 approved these changes

2025-01-31 22:15 UTC, PatrykPaluch approved these changes

2025-02-01 21:15 UTC, merged